In [2]:
import pandas as pd
from IPython.display import display

# ============================================================
# 0. Load cleaned firm-level and macro datasets
# ============================================================

kpi_clean_path = "../data/processed/compustat_kpis_clean.csv"
kpi_scaled_path = "../data/processed/compustat_kpis_clean_scaled.csv"

macro_clean_path = "../data/processed/macro_clean.csv"
macro_scaled_path = "../data/processed/macro_clean_scaled.csv"

df_firm = pd.read_csv(kpi_clean_path)
df_firm_scaled = pd.read_csv(kpi_scaled_path)

df_macro = pd.read_csv(macro_clean_path)
df_macro_scaled = pd.read_csv(macro_scaled_path)

print("Firm-level clean shape:", df_firm.shape)
print("Macro clean shape:", df_macro.shape)

# ============================================================
# 1. Prepare merge keys
# ============================================================

df_firm["fyear"] = pd.to_numeric(df_firm["fyear"], errors="coerce").astype("Int64")
df_firm_scaled["fyear"] = pd.to_numeric(df_firm_scaled["fyear"], errors="coerce").astype("Int64")

df_macro["year"] = pd.to_numeric(df_macro["year"], errors="coerce").astype("Int64")
df_macro_scaled["year"] = pd.to_numeric(df_macro_scaled["year"], errors="coerce").astype("Int64")

print("\nFirm fyear range:", df_firm["fyear"].min(), "→", df_firm["fyear"].max())
print("Macro year range:", df_macro["year"].min(), "→", df_macro["year"].max())

# ============================================================
# 2. Identify macro columns
# ============================================================

macro_id_cols = ["year"]
macro_var_cols = [c for c in df_macro.columns if c not in macro_id_cols]

macro_scaled_var_cols = [c for c in df_macro_scaled.columns if c not in ["year"]]

# ============================================================
# 3. Merge UN-SCALED: firm_clean + macro_clean
# ============================================================

df_merged = df_firm.merge(
    df_macro,
    left_on="fyear",
    right_on="year",
    how="left",
    suffixes=("", "_macro")
)

if "year" in df_merged.columns:
    df_merged = df_merged.drop(columns=["year"])

print("\nMerged (unscaled) dataset shape:", df_merged.shape)
display(df_merged.head())

# ============================================================
# 4. Merge SCALED: firm_scaled + macro_scaled
# ============================================================

df_merged_scaled = df_firm_scaled.merge(
    df_macro_scaled,
    left_on="fyear",
    right_on="year",
    how="left",
    suffixes=("", "_macro")
)

if "year" in df_merged_scaled.columns:
    df_merged_scaled = df_merged_scaled.drop(columns=["year"])

print("\nMerged (scaled) dataset shape:", df_merged_scaled.shape)
display(df_merged_scaled.head())

# ============================================================
# 5. Save merged datasets (NOW INTO /data/final/)
# ============================================================

output_merged = "../data/final/firm_macro_merged.csv"
output_merged_scaled = "../data/final/firm_macro_merged_scaled.csv"

df_merged.to_csv(output_merged, index=False)
df_merged_scaled.to_csv(output_merged_scaled, index=False)

print("\nSaved merged unscaled dataset to:", output_merged)
print("Saved merged scaled dataset to:", output_merged_scaled)

# ============================================================
# Summary
# ============================================================

print("\nSummary:")
print("  Firm-level clean:", df_firm.shape)
print("  Macro clean:", df_macro.shape)
print("  Merged unscaled:", df_merged.shape)
print("  Merged scaled:", df_merged_scaled.shape)

Firm-level clean shape: (240308, 23)
Macro clean shape: (32, 7)

Firm fyear range: 1994 → 2024
Macro year range: 1994 → 2025

Merged (unscaled) dataset shape: (240308, 29)

,gvkey,datadate,fyear,conm,tic,dlrsn,bankruptcy_dlrsn,roa,ebitda_margin,debt_ratio,...,book_to_market,price_to_book,working_capital_to_assets,retained_earnings_to_assets,name,us_gdp_(ar)_cura,us_cpi_-_all_urban:_all_items_sadj,us_treasury_bill_rate_-_3_month_(ep)_nadj,us_treasury_yield_adjusted_to_constant_maturity_-_20_year_nadj,us_unemployment_rate_sadj
0,1004,1995-05-31,1994,AAR CORP,AIR,NaN,0,0.031793,0.077019,0.537077,...,0.460255,1.234818,0.583569,0.240565,1994.31,7396.51572,149.51398,5.70,7.3257,6.1
1,1004,1996-05-31,1995,AAR CORP,AIR,NaN,0,0.049849,0.084273,0.532632,...,0.460255,1.729691,0.590680,0.250182,1995.00,7639.74900,152.38300,5.08,6.9600,5.6
2,1004,1997-05-31,1996,AAR CORP,AIR,NaN,0,0.060621,0.093627,0.491565,...,0.460255,2.095840,0.593143,0.231646,1996.00,8073.12200,156.85800,5.15,6.8200,5.4
3,1004,1998-05-31,1997,AAR CORP,AIR,NaN,0,0.074896,0.101006,0.551344,...,0.460255,2.434527,0.476098,0.220100,1997.00,8577.55300,160.52500,5.35,6.6800,4.9
4,1004,1999-05-31,1998,AAR CORP,AIR,NaN,0,0.080941,0.102876,0.551305,...,0.602903,1.658646,0.460482,0.245524,1998.00,9062.81700,163.00800,4.47,5.7200,4.5

Merged (scaled) dataset shape: (240308, 29)

,gvkey,datadate,fyear,conm,tic,dlrsn,bankruptcy_dlrsn,roa,ebitda_margin,debt_ratio,...,book_to_market,price_to_book,working_capital_to_assets,retained_earnings_to_assets,name,us_gdp_(ar)_cura,us_cpi_-_all_urban:_all_items_sadj,us_treasury_bill_rate_-_3_month_(ep)_nadj,us_treasury_yield_adjusted_to_constant_maturity_-_20_year_nadj,us_unemployment_rate_sadj
0,1004,1995-05-31,1994,AAR CORP,AIR,NaN,0,0.226063,0.171086,-0.181664,...,-0.003440,-0.148203,0.372367,0.214576,-1.624936,-1.398798,-1.499747,1.514148,1.871440,0.317004
1,1004,1996-05-31,1995,AAR CORP,AIR,NaN,0,0.238559,0.171952,-0.183780,...,-0.003440,-0.087432,0.376548,0.215062,-1.551124,-1.357335,-1.434948,1.229085,1.641494,0.014970
2,1004,1997-05-31,1996,AAR CORP,AIR,NaN,0,0.246015,0.173069,-0.203332,...,-0.003440,-0.042469,0.377995,0.214125,-1.444150,-1.283458,-1.333876,1.261269,1.553465,-0.105844
3,1004,1998-05-31,1997,AAR CORP,AIR,NaN,0,0.255895,0.173950,-0.174871,...,-0.003440,-0.000877,0.309188,0.213540,-1.337176,-1.197468,-1.251054,1.353225,1.465435,-0.407879
4,1004,1999-05-31,1998,AAR CORP,AIR,NaN,0,0.260078,0.174173,-0.174890,...,0.138547,-0.096157,0.300008,0.214827,-1.230202,-1.114746,-1.194974,0.948620,0.861805,-0.649506

Saved merged unscaled dataset to: ../data/final/firm_macro_merged.csv
Saved merged scaled dataset to: ../data/final/firm_macro_merged_scaled.csv

Summary:
  Firm-level clean: (240308, 23)
  Macro clean: (32, 7)
  Merged unscaled: (240308, 29)
  Merged scaled: (240308, 29)